# Generated by Django 2.2 on 2019-05-14 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='altmenu',
            name='ust_menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='help_docs.UstMenu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='altmenu',
            name='menu_isim',
            field=models.CharField(max_length=30, verbose_name='Kategori İsim'),
        ),
        migrations.AlterField(
            model_name='ustmenu',
            name='isim',
            field=models.CharField(max_length=30, verbose_name='Kategori İsim'),
        ),
    ]
