# Generated by Django 2.2 on 2019-05-16 13:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_docs', '0002_auto_20190514_1058'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazi', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='altmenu',
            name='ust_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help_docs.UstMenu'),
        ),
    ]
