# Generated by Django 2.2 on 2019-05-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_docs', '0003_auto_20190516_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2500, verbose_name='İçerik')),
                ('alt_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help_docs.AltMenu')),
                ('ust_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='help_docs.UstMenu')),
            ],
            options={
                'verbose_name_plural': 'İçerik',
            },
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
