# Generated by Django 2.2 on 2019-05-17 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('help_docs', '0004_auto_20190517_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_title',
            name='alt_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='help_docs.AltMenu'),
        ),
    ]
