# Generated by Django 2.2 on 2019-05-20 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_docs', '0006_auto_20190520_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new_content',
            new_name='NewContent',
        ),
    ]
