# Generated by Django 2.2 on 2019-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_docs', '0008_auto_20190520_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_content_list', 'İçerik sekmesini görebilir.'), ('view_new_Content', 'İçerik oluşturulduğu sekmeyi görebilir.'), ('view_show_content', 'İçerik sekmesini görebilir.'), ('view_alt_menu_olustur', 'Alt menü sekmesini görebilir.'), ('view_ust_menu_olustur', 'Üst menü sekmesini görebilir.')),
                'managed': False,
            },
        ),
    ]
