# Generated by Django 2.2 on 2019-05-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('help_docs', '0010_document'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewpermissions',
            options={'managed': False, 'permissions': (('view_content_list', 'İçerik sekmesini görebilir.'), ('view_new_Content', 'İçerik oluşturulduğu sekmeyi görebilir.'), ('view_show_content', 'İçerik sekmesini görebilir.'), ('view_alt_menu_olustur', 'Alt menü sekmesini görebilir.'), ('view_ust_menu_olustur', 'Üst menü sekmesini görebilir.'), ('view_image_gallery', 'Image sekmesini görebilir.'))},
        ),
    ]
