# Generated by Django 2.2 on 2019-05-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_docs', '0011_auto_20190527_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='altmenu',
            name='menu_isim',
            field=models.CharField(max_length=100, verbose_name='Kategori İsim'),
        ),
    ]
