# Generated by Django 2.2 on 2019-05-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help_docs', '0012_auto_20190527_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ustmenu',
            name='isim',
            field=models.CharField(max_length=100, verbose_name='Kategori İsim'),
        ),
    ]
